# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: Gradle@2
  inputs:
    gradleWrapperFile: '$(system.defaultWorkingDirectory)/android/gradlew'
    workingDirectory: '$(system.defaultWorkingDirectory)/android'
    tasks: 'assembleRelease'
    gradleOptions: '-Xmx3072m'
    testResultsFiles: '**/TEST-*.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    itemPattern: '**/*.apk'
    targetPath: '$(Pipeline.Workspace)'